sudo: required
dist: precise

language: go
go:
 - 1.7.5

env:
 secure: "Vz5hfOXC/z8IxvN93UlkBfOSh8zBZT2y96UK0WU16OqSaXpFSIrUkp1fSZJln/UAai13DQ/Dqyq8+0R4JHyLCSyjI+mCmA2JBpy06+wrBeMlHp5ocrl4/RkXUw2/UUhJOIvQPB8WF5IXIjiLtoRn0bJlifQ+l94o+HFiWqNndwTDFa78NN4HdwzDuR6BM+6153rTAFfbLVnaMdHZVM7AEm15K8TAVKMBNZHRc2q6txp8limzMyzUTr7q0d48B485JsUs/Qe4ZIDDfUZzC0ObJmjjxIuynHf/CZT5ChTyHhvyPJR8o9nyq1yKDmLpwZG6Hv+xr0u4p/9hwqTIfRsk09Gmtos9pZfAP1yjVkC+pxA8KcbNPps0/ELR5ooG7JpSdEnDnPSpwlDX7mcqv3k6efTKA6o/asVvSBzZ98QjsTpE8qtQoYtvjcD0UQB4pI2B835MaNULhqX60GMAdt3ou4YwtlSs1EfT3HSvEHO1FTXKndNFoWdvlPwj2IzHbxsn4TVXoqlihJ9NqqekSy+TptopOdK5IJlKw4U4OXZ5sMADC1TxLww1hlhtQ689tcqwYpIJ5YiTppQ96BjbyT+016iD7bsnAltCJY++DVRjNtpE97yEmpBre8U+8UgEyu1EXGQZoqEZhO7M8baz7lEpzJn+d7SvdcZ2oHKm8p5qXzo="

install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls
 - go get -u github.com/kardianos/govendor
 - govendor sync
 - curl -sSL "https://get.docker.com/gpg" | sudo -E apt-key add -
 - echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update
 - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes --force-yes install docker-engine
 - sudo docker version
 - sudo pip install docker-compose
 - docker-compose version

before_script:
 - cd ci
 - sudo docker-compose up --build -d
 - echo "Waiting 10 seconds for Kafka / Zookeeper / Elasticsearch to start up..."
 - sleep 10
 - sudo ./create_topics.sh
 - go run populate_topics.go
 - cd ../../

script:
 - go test . -v -covermode=count -coverprofile=coverage.out
 - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

after_script:
 - cd integration_tests/kafka
 - sudo docker-compose down
